#!/usr/bin/env node

const fs   = require('fs');
const path = require('path');

const runId    = process.argv[2];
const agentrc  = JSON.parse(fs.readFileSync('.agentrc', 'utf-8'));

if (!runId) {
  console.error('Usage: node pr-builder.js <run_id>');
  process.exit(1);
}

const payloadPath = path.join(agentrc.agent.payloadDir, `run_${runId}.json`);
if (!fs.existsSync(payloadPath)) {
  console.error(`Payload not found: ${payloadPath}`);
  process.exit(1);
}

const payload = JSON.parse(fs.readFileSync(payloadPath, 'utf-8'));
const { normalised, phase_outputs, meta } = payload;
const design    = phase_outputs.design    || {};
const implement = phase_outputs.implement || {};
const evaluate  = phase_outputs.evaluate  || {};

// Build PR title
const title = `[${meta.ticket_id}] ${normalised.feature_summary}`;

// Build PR body
const lines = [];

lines.push(`## What`);
lines.push(normalised.feature_summary);
lines.push('');

lines.push(`## Jira`);
lines.push(`[${meta.ticket_id}](${agentrc.jira.baseUrl}/browse/${meta.ticket_id})`);
lines.push('');

lines.push(`## Screen`);
if (normalised.requires_design) {
  lines.push(`\`${normalised.screen_name}\` — UI type: \`${normalised.ui_type}\``);
} else {
  lines.push(`Technical-only change — no UI/design work. Affected: \`${normalised.screen_name}\``);
}
lines.push('');

lines.push(`## Files changed`);
(design.files_created || []).forEach(f => lines.push(`- ✨ \`${f}\` (created)`));
(design.files_modified || []).forEach(f => lines.push(`- 📝 \`${f}\` (modified)`));
(implement.files_created || []).forEach(f => lines.push(`- ✨ \`${f}\` (created)`));
(implement.files_modified || []).forEach(f => lines.push(`- 📝 \`${f}\` (modified)`));
lines.push('');

if (normalised.requires_design && !design.skipped) {
  lines.push(`## Pixel match`);
  lines.push(`- Final score: **${design.pixel_match?.final_score}%** (threshold: ${agentrc.evaluate.pixelMatchThreshold}%)`);
  lines.push(`- Attempts: ${design.pixel_match?.attempts}`);
  lines.push(`- States verified: ${design.pixel_match?.states_verified}`);
  lines.push('');
}

lines.push(`## Tests`);
lines.push(`- Unit tests: ${implement.unit_tests_written || 0} written`);
lines.push(`- UI tests: ${implement.ui_tests_written || 0} written`);
lines.push(`- All existing tests: ✅ passing`);
lines.push('');

// Flags
const flags = normalised.flags || [];
if (flags.length > 0) {
  lines.push(`## ⚠ Agent flags — please review`);
  flags.forEach(f => lines.push(`- **${f.type}**: ${f.message}`));
  lines.push('');
}

// Overrides
if (meta.ac_override) {
  lines.push(`> ⚠ AC was missing — acceptance criteria were inferred by the agent. Please verify.`);
}
if (meta.scope_override) {
  lines.push(`> ⚠ Scope override — developer acknowledged multiple screens.`);
}

// Localisation
const i18n = evaluate.localisation || {};
if (i18n.placeholders_added > 0) {
  lines.push('');
  lines.push(`## 🌐 Localisation`);
  lines.push(`${i18n.placeholders_added} string keys need translation — marked with \`[NEEDS_TRANSLATION]\``);
  lines.push(`Languages: ${(agentrc.languages || []).join(', ')}`);
}

lines.push('');
lines.push(`---`);
lines.push(`*Generated by Android Agentic Dev Tool — confidence: ${meta.confidence_score}*`);

// Output for Claude Code to use with gh CLI
const output = {
  title,
  body: lines.join('\n'),
  branch: `${agentrc.ci.branchPrefix}${meta.ticket_id.toLowerCase()}-${normalised.screen_name.toLowerCase()}`,
  base: agentrc.ci.defaultBranch
};

console.log(JSON.stringify(output, null, 2));